#Dependent Jobs Example
name: "Dependent Jobs example"

on: ["push"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: "First Step"
        run: echo "This is job 1"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: "Second Step"
        run: echo "This is job 2, which depends on job 1"
